"use client";

import * as React from "react";
import { ChevronDown, Save, Loader2, Check, Plus, Trash2 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { LifeOsData } from "@/lib/life-os/types";

/**
 * Simplified Life OS form — only asks for essentials.
 * Diet, workout split, detailed schedule, etc. are GENERATED by the AI planner.
 */

type SaveState = "idle" | "saving" | "saved" | "error";

function num(v: string): number | undefined {
  const n = parseFloat(v);
  return Number.isFinite(n) ? n : undefined;
}

function intNum(v: string): number | undefined {
  const n = parseInt(v, 10);
  return Number.isFinite(n) ? n : undefined;
}

function Section({
  title,
  emoji,
  hint,
  children,
  defaultOpen = false,
}: {
  title: string;
  emoji?: string;
  hint?: string;
  children: React.ReactNode;
  defaultOpen?: boolean;
}) {
  const [open, setOpen] = React.useState(defaultOpen);
  return (
    <Card className="overflow-hidden">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="w-full text-left"
      >
        <CardHeader className="flex flex-row items-center justify-between py-4">
          <div className="flex items-center gap-2">
            {emoji && <span className="text-lg">{emoji}</span>}
            <div>
              <CardTitle className="text-sm font-semibold">{title}</CardTitle>
              {hint && <p className="mt-0.5 text-[11px] text-stone-500">{hint}</p>}
            </div>
          </div>
          <ChevronDown
            className={`h-4 w-4 shrink-0 text-stone-400 transition-transform ${open ? "rotate-180" : ""}`}
          />
        </CardHeader>
      </button>
      {open && <CardContent className="space-y-3 pt-0">{children}</CardContent>}
    </Card>
  );
}

function Field({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="space-y-1">
      <Label className="text-[11px] uppercase tracking-wide text-stone-500">{label}</Label>
      {children}
    </div>
  );
}

const FITNESS_GOALS = [
  { value: "lean", label: "Lean / Toned", desc: "Low body fat, defined muscles" },
  { value: "athletic", label: "Athletic", desc: "Strong, functional, balanced" },
  { value: "bulk", label: "Bulk / Mass", desc: "Maximum muscle gain" },
  { value: "weight-loss", label: "Weight Loss", desc: "Lose weight, feel better" },
  { value: "maintain", label: "Maintain", desc: "Keep current shape" },
  { value: "none", label: "No fitness goal", desc: "Skip gym planning" },
];

export function LifeOsForm({
  initial,
  onSaved,
}: {
  initial: LifeOsData;
  onSaved?: (data: LifeOsData) => void;
}) {
  const [data, setData] = React.useState<LifeOsData>(initial);
  const [state, setState] = React.useState<SaveState>("idle");
  const [error, setError] = React.useState<string | null>(null);
  const [hasDebt, setHasDebt] = React.useState(!!initial.finances?.totalDebtEUR);

  const patch = <K extends keyof LifeOsData>(key: K, value: LifeOsData[K]) => {
    setData((d) => ({ ...d, [key]: value }));
  };

  const save = async () => {
    setState("saving");
    setError(null);
    try {
      const res = await fetch("/api/life-os", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data),
      });
      if (!res.ok) {
        const j = (await res.json().catch(() => ({}))) as { error?: string };
        throw new Error(j.error ?? "Save failed");
      }
      const j = (await res.json()) as { profile: LifeOsData };
      setState("saved");
      onSaved?.(j.profile);
      setTimeout(() => setState("idle"), 1800);
    } catch (e) {
      setState("error");
      setError(e instanceof Error ? e.message : "Save failed");
    }
  };

  // ─── Year goals helpers ────────────────────────────────────────────
  const yearGoals = data.yearGoals ?? [];
  const addYearGoal = () => patch("yearGoals", [...yearGoals, { title: "" }]);
  const updateYearGoal = (i: number, p: Partial<NonNullable<LifeOsData["yearGoals"]>[number]>) =>
    patch("yearGoals", yearGoals.map((g, idx) => (idx === i ? { ...g, ...p } : g)));
  const removeYearGoal = (i: number) =>
    patch("yearGoals", yearGoals.filter((_, idx) => idx !== i));

  // ─── Projects array helpers ────────────────────────────────────────
  const projects = data.projects ?? [];
  const addProject = () =>
    patch("projects", [...projects, { name: "", description: "", weeklyHoursTarget: 0 }]);
  const updateProject = (i: number, patchP: Partial<NonNullable<LifeOsData["projects"]>[number]>) =>
    patch("projects", projects.map((p, idx) => (idx === i ? { ...p, ...patchP } : p)));
  const removeProject = (i: number) =>
    patch("projects", projects.filter((_, idx) => idx !== i));

  // ─── Rules helpers ────────────────────────────────────────────────
  const rules = data.rules ?? {};
  const nonNegs = rules.nonNegotiables ?? [];
  const hardStops = rules.hardStops ?? [];
  const setRule = (k: "nonNegotiables" | "hardStops", arr: string[]) =>
    patch("rules", { ...rules, [k]: arr });

  return (
    <div className="space-y-3">

      {/* ─── About you ──────────────────────────────────────── */}
      <Section title="About you" emoji="👤" hint="The basics" defaultOpen>
        <div className="grid grid-cols-2 gap-3">
          <Field label="Name">
            <Input
              value={data.identity?.name ?? ""}
              onChange={(e) => patch("identity", { ...data.identity, name: e.target.value })}
              placeholder="Your name"
            />
          </Field>
          <Field label="Age">
            <Input
              type="number"
              value={data.identity?.age ?? ""}
              onChange={(e) => patch("identity", { ...data.identity, age: intNum(e.target.value) })}
            />
          </Field>
          <Field label="Weight (kg)">
            <Input
              type="number"
              value={data.identity?.currentWeightKg ?? ""}
              onChange={(e) => patch("identity", { ...data.identity, currentWeightKg: num(e.target.value) })}
            />
          </Field>
          <Field label="Height (cm)">
            <Input
              type="number"
              value={data.identity?.heightCm ?? ""}
              onChange={(e) => patch("identity", { ...data.identity, heightCm: num(e.target.value) })}
            />
          </Field>
          <Field label="Wake up">
            <Input
              type="time"
              value={data.identity?.wakeTime ?? ""}
              onChange={(e) => patch("identity", { ...data.identity, wakeTime: e.target.value })}
            />
          </Field>
          <Field label="Sleep">
            <Input
              type="time"
              value={data.identity?.sleepTime ?? ""}
              onChange={(e) => patch("identity", { ...data.identity, sleepTime: e.target.value })}
            />
          </Field>
        </div>
        <Field label="Location">
          <Input
            value={data.identity?.location ?? ""}
            onChange={(e) => patch("identity", { ...data.identity, location: e.target.value })}
            placeholder="City, Country"
          />
        </Field>
      </Section>

      {/* ─── Schedule essentials ─────────────────────────────── */}
      <Section title="Schedule" emoji="📅" hint="Your fixed commitments — we fill the rest">
        <p className="text-[11px] text-stone-500 -mt-1">
          Tell us your work/study hours. AIAH builds the rest of your week around these.
        </p>
        <Field label="Work hours (e.g. Mon-Wed 9-17h)">
          <Textarea
            rows={2}
            value={data.weeklySchedule?.monday ?? ""}
            onChange={(e) => patch("weeklySchedule", { ...data.weeklySchedule, monday: e.target.value })}
            placeholder="Mon, Tue, Wed: 9:00-17:00 office&#10;Thu, Fri: 9:00-16:00 school"
          />
        </Field>
        <Field label="Other fixed commitments">
          <Textarea
            rows={2}
            value={data.weeklySchedule?.saturday ?? ""}
            onChange={(e) => patch("weeklySchedule", { ...data.weeklySchedule, saturday: e.target.value })}
            placeholder="Saturday: freelancing&#10;Sunday: rest / meal prep"
          />
        </Field>
      </Section>

      {/* ─── Fitness goal ────────────────────────────────────── */}
      <Section title="Body goal" emoji="💪" hint="Pick your goal — we design your workout + diet">
        <div className="grid grid-cols-2 gap-2">
          {FITNESS_GOALS.map((g) => {
            const active = data.fitness?.goal === g.value;
            return (
              <button
                key={g.value}
                type="button"
                onClick={() => patch("fitness", { ...data.fitness, goal: g.value })}
                className={`rounded-xl border p-3 text-left transition-all ${
                  active
                    ? "border-[#1D9E75] bg-emerald-50/80 dark:border-emerald-500/50 dark:bg-emerald-950/30"
                    : "border-stone-200/60 hover:bg-stone-50 dark:border-white/[0.06] dark:hover:bg-white/[0.04]"
                }`}
              >
                <p className="text-xs font-semibold text-stone-800 dark:text-stone-200">{g.label}</p>
                <p className="text-[10px] text-stone-500 mt-0.5">{g.desc}</p>
              </button>
            );
          })}
        </div>
        <Field label="Target weight (optional)">
          <Input
            type="number"
            value={data.fitness?.stepsTarget ?? ""}
            onChange={(e) => patch("fitness", { ...data.fitness, stepsTarget: intNum(e.target.value) })}
            placeholder="e.g. 80"
          />
        </Field>
      </Section>

      {/* ─── Money ──────────────────────────────────────────── */}
      <Section title="Money" emoji="💰" hint="Income and payments">
        <Field label="Monthly income (€)">
          <Input
            type="number"
            value={data.finances?.monthlyIncomeEUR ?? ""}
            onChange={(e) => patch("finances", { ...data.finances, monthlyIncomeEUR: num(e.target.value) })}
          />
        </Field>
        <Field label="Monthly fixed expenses (€)">
          <Input
            type="number"
            value={data.finances?.monthlyFixedExpensesEUR ?? ""}
            onChange={(e) => patch("finances", { ...data.finances, monthlyFixedExpensesEUR: num(e.target.value) })}
            placeholder="Rent, bills, subscriptions..."
          />
        </Field>

        {/* Debt checkbox */}
        <div className="flex items-center gap-2 mt-1">
          <button
            type="button"
            onClick={() => {
              setHasDebt(!hasDebt);
              if (hasDebt) {
                patch("finances", { ...data.finances, totalDebtEUR: undefined, debtPayoffTarget: undefined });
              }
            }}
            className={`flex h-5 w-5 items-center justify-center rounded-md border-2 transition-colors ${
              hasDebt
                ? "border-[#1D9E75] bg-[#1D9E75]"
                : "border-stone-300 dark:border-stone-600"
            }`}
          >
            {hasDebt && <Check className="h-3.5 w-3.5 text-white" />}
          </button>
          <span className="text-xs text-stone-600 dark:text-stone-400">I have debt to pay off</span>
        </div>

        {hasDebt && (
          <div className="grid grid-cols-2 gap-3 mt-2 pl-7">
            <Field label="Total debt (€)">
              <Input
                type="number"
                value={data.finances?.totalDebtEUR ?? ""}
                onChange={(e) => patch("finances", { ...data.finances, totalDebtEUR: num(e.target.value) })}
              />
            </Field>
            <Field label="Pay off by">
              <Input
                value={data.finances?.debtPayoffTarget ?? ""}
                onChange={(e) => patch("finances", { ...data.finances, debtPayoffTarget: e.target.value })}
                placeholder="Dec 2026"
              />
            </Field>
          </div>
        )}
      </Section>

      {/* ─── Year goals ─────────────────────────────────────── */}
      <Section title="Year goals" emoji="🎯" hint="3-6 outcomes that define your year">
        <div className="space-y-2">
          {yearGoals.map((g, i) => (
            <div key={i} className="flex items-center gap-2">
              <Input
                value={g.title}
                onChange={(e) => updateYearGoal(i, { title: e.target.value })}
                placeholder="e.g. Pay off all debt"
                className="flex-1"
              />
              <Input
                value={g.deadline ?? ""}
                onChange={(e) => updateYearGoal(i, { deadline: e.target.value })}
                placeholder="Dec 2026"
                className="w-24"
              />
              <Button type="button" variant="ghost" size="icon" onClick={() => removeYearGoal(i)}>
                <Trash2 className="h-4 w-4" />
              </Button>
            </div>
          ))}
          <Button type="button" variant="outline" onClick={addYearGoal} className="rounded-xl text-xs">
            <Plus className="h-3.5 w-3.5 mr-1" /> Add goal
          </Button>
        </div>
      </Section>

      {/* ─── Income growth ──────────────────────────────────── */}
      <Section title="Side income" emoji="📈" hint="Freelance, business, side hustles">
        <div className="grid grid-cols-2 gap-3">
          <Field label="Current monthly (€)">
            <Input
              type="number"
              value={data.income?.currentMonthlyEUR ?? ""}
              onChange={(e) => patch("income", { ...data.income, currentMonthlyEUR: num(e.target.value) })}
            />
          </Field>
          <Field label="Target monthly (€)">
            <Input
              type="number"
              value={data.income?.targetMonthlyEUR ?? ""}
              onChange={(e) => patch("income", { ...data.income, targetMonthlyEUR: num(e.target.value) })}
            />
          </Field>
        </div>
        <Field label="What do you offer?">
          <Input
            value={data.income?.primaryOffer ?? ""}
            onChange={(e) => patch("income", { ...data.income, primaryOffer: e.target.value })}
            placeholder="Digital marketing, consulting, dev..."
          />
        </Field>
      </Section>

      {/* ─── Projects ───────────────────────────────────────── */}
      <Section title="Projects" emoji="🚀" hint="What you&apos;re building">
        <div className="space-y-2">
          {projects.map((p, i) => (
            <div key={i} className="rounded-xl border border-stone-200 dark:border-stone-800 p-3 space-y-2">
              <div className="flex items-center gap-2">
                <Input
                  value={p.name}
                  onChange={(e) => updateProject(i, { name: e.target.value })}
                  placeholder="Project name"
                  className="flex-1"
                />
                <Button type="button" variant="ghost" size="icon" onClick={() => removeProject(i)}>
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
              <div className="grid grid-cols-2 gap-2">
                <Field label="Hours/week">
                  <Input
                    type="number"
                    value={p.weeklyHoursTarget ?? ""}
                    onChange={(e) => updateProject(i, { weeklyHoursTarget: num(e.target.value) })}
                  />
                </Field>
                <Field label="Deadline">
                  <Input
                    value={p.deadline ?? ""}
                    onChange={(e) => updateProject(i, { deadline: e.target.value })}
                    placeholder="Sept 2026"
                  />
                </Field>
              </div>
            </div>
          ))}
          <Button type="button" variant="outline" onClick={addProject} className="rounded-xl text-xs">
            <Plus className="h-3.5 w-3.5 mr-1" /> Add project
          </Button>
        </div>
      </Section>

      {/* ─── Rules ──────────────────────────────────────────── */}
      <Section title="Rules" emoji="🛡️" hint="Non-negotiables the planner must respect">
        <Field label="Non-negotiables (one per line)">
          <Textarea
            rows={3}
            value={nonNegs.join("\n")}
            onChange={(e) =>
              setRule("nonNegotiables", e.target.value.split("\n").map((l) => l.trim()).filter(Boolean))
            }
            placeholder={"Gym 5x/week\n7h sleep minimum\nNo phone first 30min"}
          />
        </Field>
        <Field label="Hard stops (one per line)">
          <Textarea
            rows={2}
            value={hardStops.join("\n")}
            onChange={(e) =>
              setRule("hardStops", e.target.value.split("\n").map((l) => l.trim()).filter(Boolean))
            }
            placeholder={"No unplanned spending\nNo skipping meals"}
          />
        </Field>
      </Section>

      {/* ─── Save bar ───────────────────────────────────────── */}
      <div className="sticky bottom-16 z-10 flex items-center justify-between gap-3 rounded-2xl border border-stone-200 bg-white/90 px-4 py-3 shadow-lg backdrop-blur-xl dark:border-stone-800 dark:bg-stone-900/90 md:bottom-6">
        <div className="text-sm">
          {state === "saved" && (
            <span className="flex items-center gap-1 text-emerald-600">
              <Check className="h-4 w-4" /> Saved
            </span>
          )}
          {state === "error" && <span className="text-rose-600">{error ?? "Error"}</span>}
          {state === "idle" && (
            <span className="text-xs text-stone-500">Save, then generate your week.</span>
          )}
        </div>
        <Button onClick={() => void save()} disabled={state === "saving"} className="rounded-xl">
          {state === "saving" ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <Save className="h-4 w-4" />
          )}
          <span className="ml-2">Save</span>
        </Button>
      </div>
    </div>
  );
}
